In [1]:
import pandas as  pd
import matplotlib as mpl
import numpy as np
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from imblearn.over_sampling import SMOTE
from pyod.models.abod import ABOD

In [2]:
train = pd.read_csv("training.csv",sep=';')
test = pd.read_csv("validation.csv",sep=';')
    
train.head(30)

,variable1,variable2,variable3,variable4,variable5,variable6,variable7,variable8,variable9,variable10,variable11,variable12,variable13,variable14,variable15,variable17,variable18,variable19,classLabel
0,a,"17,92","5,4e-05",u,g,c,v,"1,75",f,t,1,t,g,80.0,5,800000.0,t,0,no.
1,b,"16,92","3,35e-05",y,p,k,v,"0,29",f,f,0,f,s,200.0,0,2000000.0,NaN,0,no.
2,b,"31,25","0,0001125",u,g,ff,ff,0,f,t,1,f,g,96.0,19,960000.0,t,0,no.
3,a,"48,17","0,0001335",u,g,i,o,"0,335",f,f,0,f,g,0.0,120,0.0,NaN,0,no.
4,b,"32,33","0,00035",u,g,k,v,"0,5",f,f,0,t,g,232.0,0,2320000.0,f,0,no.
5,a,"34,83","0,000125",y,p,i,h,"0,5",f,f,0,t,g,160.0,0,1600000.0,f,0,no.
6,a,"26,17",2e-04,u,g,j,j,0,f,f,0,t,g,276.0,1,2760000.0,NaN,0,no.
7,b,"21,17","8,75e-05",y,p,c,h,"0,25",f,f,0,f,g,280.0,204,2800000.0,NaN,0,no.
8,b,"28,92","3,75e-05",u,g,c,v,"0,29",f,f,0,f,g,220.0,140,2200000.0,NaN,0,no.
9,b,"18,17","0,001025",u,g,c,h,"1,085",f,f,0,f,g,320.0,13,3200000.0,NaN,0,no.
10,a,"24,75","0,0013665",u,g,q,h,"1,5",f,f,0,f,g,280.0,1,2800000.0,f,0,no.
11,a,"31,75",3e-04,y,p,j,j,0,f,f,0,f,g,160.0,20,1600000.0,f,0,no.
12,a,"18,17","0,001",y,p,q,h,"0,165",f,f,0,f,g,340.0,0,3400000.0,f,0,no.
13,a,"18,25","0,001",u,g,W,v,1,f,t,1,f,g,120.0,1,1200000.0,NaN,0,no.
14,b,"17,58","0,001",u,g,W,h,"0,165",f,t,1,f,g,120.0,1,1200000.0,t,0,no.
15,b,"51,83","0,000204",y,p,ff,ff,"1,5",f,f,0,f,g,120.0,1,1200000.0,NaN,0,no.
16,b,"26,67","0,0014585",u,g,i,bb,0,f,f,0,t,g,178.0,0,1780000.0,f,0,no.
17,b,"31,42","0,00155",u,g,c,v,"0,5",t,f,0,f,g,120.0,0,1200000.0,f,0,no.
18,b,"25,67","0,000325",u,g,c,h,"2,29",f,t,1,t,g,416.0,21,4160000.0,t,0,no.
19,b,"33,75","0,000275",u,g,i,bb,0,f,f,0,f,g,180.0,0,1800000.0,f,0,no.
20,b,"32,75","0,0002335",u,g,d,h,"5,75",f,f,0,t,g,292.0,0,2920000.0,f,0,no.
21,b,"39,83",5e-05,u,g,m,v,"0,25",t,f,0,f,s,288.0,0,2880000.0,NaN,0,no.
22,a,"40,33","0,0008125",y,p,k,v,"0,165",f,t,2,f,g,NaN,18,NaN,NaN,0,no.
23,b,"35,25","0,00165",y,p,c,v,4,t,f,0,f,g,80.0,0,800000.0,NaN,0,no.
24,a,"24,33","0,00025",y,p,i,bb,"4,5",f,f,0,f,g,200.0,456,2000000.0,f,0,no.
25,a,"15,75","3,75e-05",u,g,c,v,1,f,f,0,f,g,120.0,18,1200000.0,f,0,no.
26,a,45,"0,0004585",u,g,k,h,1,f,f,0,t,s,240.0,0,2400000.0,NaN,0,no.
27,a,"30,42","0,0001375",u,g,W,h,"0,04",f,t,3,f,g,0.0,33,0.0,NaN,0,no.
28,a,NaN,"0,00035",u,g,d,v,3,t,f,0,t,g,300.0,0,3000000.0,NaN,0,no.
29,b,"17,25",3e-04,u,g,k,v,"0,04",f,f,0,t,g,160.0,40,1600000.0,NaN,0,no.

# ********** ******** ************** **************
# Preprocessing
# ********** ******** ************** **************

In [3]:
######## see which data have been read as numric or categorial data type
categorical_feature_mask = train.dtypes==object
train.dtypes

variable1      object
variable2      object
variable3      object
variable4      object
variable5      object
variable6      object
variable7      object
variable8      object
variable9      object
variable10     object
variable11      int64
variable12     object
variable13     object
variable14    float64
variable15      int64
variable17    float64
variable18     object
variable19      int64
classLabel     object
dtype: object

In [4]:
####### so variable2 and variable3 and varaible8 can be numric so to make the decision we want to see unique values of  each variable

print  (train["variable2"].unique(),train["variable3"].unique(),train["variable8"].unique())

['17,92' '16,92' '31,25' '48,17' '32,33' '34,83' '26,17' '21,17' '28,92'
 '18,17' '24,75' '31,75' '18,25' '17,58' '51,83' '26,67' '31,42' '25,67'
 '33,75' '32,75' '39,83' '40,33' '35,25' '24,33' '15,75' '45' '30,42' nan
 '17,25' '38,58' '22,67' '49' '27,83' '16,5' '36,67' '47,25' '33,67'
 '33,17' '25' '48,5' '37,42' '18' '56,5' '25,75' '22,58' '32' '40,83'
 '59,67' '42,5' '28,08' '37,75' '53,92' '47,67' '23,25' '54,58' '34,25'
 '27,58' '46' '60,92' '47,42' '37,33' '33,25' '24,58' '21,83' '15,17'
 '22,92' '69,5' '33' '23' '22' '20,75' '20,67' '48,75' '22,75' '42,25'
 '27,67' '28,75' '23,5' '29,5' '31,92' '18,83' '26,75' '27,17' '47,17'
 '23,75' '41,58' '26,33' '39,42' '44,83' '50,75' '19,17' '21,5' '25,58'
 '20,42' '44,17' '34,75' '20,5' '22,08' '42,83' '18,92' '52,83' '36,25'
 '20,33' '28,17' '23,92' '56' '30,5' '45,83' '39' '28,25' '28,67' '22,5'
 '36,08' '20' '43,25' '52,33' '19,33' '23,58' '69,17' '24,92' '29,83'
 '23,08' '31' '22,17' '45,17' '40,58' '16,33' '35,75' '49,58' '30,25'
 '34,67' '50,25' '57,58' '24,83' '22,25' '21,08' '52,17' '28,5' '17,5'
 '34,42' '73,42' '19,42' '23,33' '42,17' '21,25' '34,17' '47,75' '44,33'
 '39,5' '41,17' '29,92' '23,17' '35,17' '52,5' '39,92' '21,33' '67,75'
 '32,67' '49,5' '21' '18,33' '16' '28,58' '38,75' '32,08' '21,75' '18,58'
 '53,33' '24,5' '25,92' '34' '49,17' '19,58' '38,33' '37,5' '28' '25,17'
 '32,92' '18,08' '20,83' '21,92' '42' '23,42' '36,75' '17,83' '22,83'
 '13,75' '41' '20,17' '50,08' '27' '29,75' '25,25' '39,17' '20,08' '44,25'
 '26,92' '27,33' '16,25' '29,25' '35' '40,92' '15,83' '36,58' '45,33'
 '36,5' '62,5' '29,58' '39,58' '38,17' '65,17' '37,58' '26' '31,67'
 '49,83' '51,33' '28,42' '56,75' '58,42' '48,33' '22,42' '48,58' '64,08'
 '31,33' '56,42' '24,08' '28,33' '19,5' '34,08' '52,42' '21,42' '31,83'
 '32,25' '38,42' '24,42' '19' '30,08' '47,33' '25,42' '42,75' '33,58'
 '38,92' '26,83' '38,67' '32,17' '39,33' '25,08' '30,67' '16,08' '47'
 '71,58' '65,42' '55,92' '34,92' '56,58' '57,83' '32,42' '17,67' '36,17'
 '27,25' '18,67' '30,75' '30,58' '43,17' '29,17' '19,67' '29,42' '25,83'
 '26,58' '30,33' '17,08' '26,25' '30,17' '57,08' '20,25' '18,5' '60,58'
 '41,5' '36' '60,08' '22,33' '40' '41,33' '46,67' '25,5' '18,75' '80,25'
 '55,75' '62,75'] ['5,4e-05' '3,35e-05' '0,0001125' '0,0001335' '0,00035' '0,000125' '2e-04'
 '8,75e-05' '3,75e-05' '0,001025' '0,0013665' '3e-04' '0,001' '0,000204'
 '0,0014585' '0,00155' '0,000325' '0,000275' '0,0002335' '5e-05'
 '0,0008125' '0,00165' '0,00025' '0,0004585' '0,0001375' '5e-04' '7,5e-05'
 '0,00015' '0,000221' '8,35e-05' '0,00085' '0,000104' '0,000175'
 '0,000425' '1,65e-05' '0,0016' '0,001075' '0,000304' '0,000154'
 '0,0004915' '0,0015' '0,00055' '0,0009625' '2,9e-05' '1e-04' '0,000254'
 '0,0009415' '4e-04' '0,00065' '6,7e-05' '7e-04' '0,0003165' '6e-04'
 '0,0001835' '7,9e-05' '0,0005085' '0,0026335' '0,00115' '0,001021'
 '0,0001165' '0,0001085' '0,0003125' '4,15e-05' '0,00045' '0,0005835'
 '0,0013' '0,000171' '0,000354' '5,85e-05' '0' '0,0006665' '8,3e-05'
 '0,0004625' '0,000925' '6,65e-05' '0,00125' '0,00105' '0,0011'
 '0,0005125' '0,0004415' '0,000846' '0,002521' '0,0010915' '4,6e-05'
 '9e-04' '0,0002835' '0,0002085' '0,00135' '0,0004085' '0,0002415'
 '0,0019' '0,000108' '0,0010085' '0,000975' '0,00095' '0,0022' '0,000271'
 '0,001775' '0,001175' '0,0011625' '0,000504' '0,000525' '8e-04'
 '0,0008585' '0,000621' '9,15e-05' '0,0007585' '0,000121' '5,8e-05'
 '0,000225' '1,7e-05' '0,000725' '0,000375' '0,000571' '6,25e-05'
 '0,000229' '0,0006165' '0,000446' '0,0009335' '2,05e-05' '0,0002875'
 '0,001275' '1,25e-05' '0,0005625' '0,001254' '2,5e-05' '0,0001665'
 '0,0002165' '0,0002665' '0,0003375' '0,000529' '0,001146' '0,000954'
 '0,0007625' '0,001029' '0,0010125' '0,000404' '0,0014' '0,0013585'
 '0,001225' '0,0021' '0,0012' '0,0005665' '0,002' '0,00195' '0,0028'
 '4e-06' '7,05e-05' '0,00145' '0,001375' '2,1e-05' '0,000146' '0,000479'
 '0,0005875' '0,0011125' '0,00185' '0,000704' '0,001125' '0,000675'
 '7,1e-05' '0,0018125' '0,0007835' '0,0001585' '0,000471' '0,0012835'
 '0,0004125' '0,000329' '0,0011585' '0,000996' '0,001479' '0,0016165'
 '0,0025125' '0,0010335' '0,001233' '0,00075' '0,000917' '0,0011045'
 '0,000708' '0,0012125'] ['1,75' '0,29' '0' '0,335' '0,5' '0,25' '1,085' '1,5' '0,165' '1' '2,29'
 '5,75' '4' '4,5' '0,04' '3' '13,5' '1,585' '2,25' '1,165' '8,5' '2,75'
 '0,375' '14' '6,5' '1,04' '0,125' '0,21' '1,46' '0,415' '2,04' '3,165'
 '8,665' '15' '0,835' '2,585' '14,415' '7,415' '2' '13,875' '4,25' '2,5'
 '0,085' '7' '11,5' '3,04' '5,5' '3,75' '1,625' '7,375' '5,375' '2,165'
 '4,58' '5,335' '2,085' '0,585' '8' '0,71' '5' '3,5' '0,665' '4,75' '2,46'
 '9,46' '2,625' '1,25' '2,54' '5,25' '3,25' '12,75' '7,875' '4,335' '0,75'
 '6,29' '13' '7,585' '5,085' '0,54' '0,875' '1,665' '0,96' '1,54' '6,04'
 '10' '1,835' '4,165' '5,665' '6' '5,125' '2,125' '1,71' '10,75' '8,29'
 '2,415' '2,375' '1,335' '16' '17,5' '1,21' '28,5' '11' '1,375' '1,29'
 '12,5' '15,5' '9' '0,46' '5,165' '20' '7,5' '0,625' '5,04' '18' '1,875'
 '3,17' '2,71' '6,75' '3,335']

In [5]:
# because they have many unique values so we will convert theem to float

def convert(numStr):
    if type(numStr)is float :
        return numStr
    numStr=numStr.replace(',','.')
    return float(numStr)
    
collumns=["variable2" ,"variable3","variable8"]
for col in collumns:
    train[col]=train[col].apply(convert)
    test[col]=test[col].apply(convert)

train.head(30)

,variable1,variable2,variable3,variable4,variable5,variable6,variable7,variable8,variable9,variable10,variable11,variable12,variable13,variable14,variable15,variable17,variable18,variable19,classLabel
0,a,17.92,0.000054,u,g,c,v,1.750,f,t,1,t,g,80.0,5,800000.0,t,0,no.
1,b,16.92,0.000034,y,p,k,v,0.290,f,f,0,f,s,200.0,0,2000000.0,NaN,0,no.
2,b,31.25,0.000112,u,g,ff,ff,0.000,f,t,1,f,g,96.0,19,960000.0,t,0,no.
3,a,48.17,0.000133,u,g,i,o,0.335,f,f,0,f,g,0.0,120,0.0,NaN,0,no.
4,b,32.33,0.000350,u,g,k,v,0.500,f,f,0,t,g,232.0,0,2320000.0,f,0,no.
5,a,34.83,0.000125,y,p,i,h,0.500,f,f,0,t,g,160.0,0,1600000.0,f,0,no.
6,a,26.17,0.000200,u,g,j,j,0.000,f,f,0,t,g,276.0,1,2760000.0,NaN,0,no.
7,b,21.17,0.000087,y,p,c,h,0.250,f,f,0,f,g,280.0,204,2800000.0,NaN,0,no.
8,b,28.92,0.000037,u,g,c,v,0.290,f,f,0,f,g,220.0,140,2200000.0,NaN,0,no.
9,b,18.17,0.001025,u,g,c,h,1.085,f,f,0,f,g,320.0,13,3200000.0,NaN,0,no.
10,a,24.75,0.001367,u,g,q,h,1.500,f,f,0,f,g,280.0,1,2800000.0,f,0,no.
11,a,31.75,0.000300,y,p,j,j,0.000,f,f,0,f,g,160.0,20,1600000.0,f,0,no.
12,a,18.17,0.001000,y,p,q,h,0.165,f,f,0,f,g,340.0,0,3400000.0,f,0,no.
13,a,18.25,0.001000,u,g,W,v,1.000,f,t,1,f,g,120.0,1,1200000.0,NaN,0,no.
14,b,17.58,0.001000,u,g,W,h,0.165,f,t,1,f,g,120.0,1,1200000.0,t,0,no.
15,b,51.83,0.000204,y,p,ff,ff,1.500,f,f,0,f,g,120.0,1,1200000.0,NaN,0,no.
16,b,26.67,0.001458,u,g,i,bb,0.000,f,f,0,t,g,178.0,0,1780000.0,f,0,no.
17,b,31.42,0.001550,u,g,c,v,0.500,t,f,0,f,g,120.0,0,1200000.0,f,0,no.
18,b,25.67,0.000325,u,g,c,h,2.290,f,t,1,t,g,416.0,21,4160000.0,t,0,no.
19,b,33.75,0.000275,u,g,i,bb,0.000,f,f,0,f,g,180.0,0,1800000.0,f,0,no.
20,b,32.75,0.000234,u,g,d,h,5.750,f,f,0,t,g,292.0,0,2920000.0,f,0,no.
21,b,39.83,0.000050,u,g,m,v,0.250,t,f,0,f,s,288.0,0,2880000.0,NaN,0,no.
22,a,40.33,0.000812,y,p,k,v,0.165,f,t,2,f,g,NaN,18,NaN,NaN,0,no.
23,b,35.25,0.001650,y,p,c,v,4.000,t,f,0,f,g,80.0,0,800000.0,NaN,0,no.
24,a,24.33,0.000250,y,p,i,bb,4.500,f,f,0,f,g,200.0,456,2000000.0,f,0,no.
25,a,15.75,0.000037,u,g,c,v,1.000,f,f,0,f,g,120.0,18,1200000.0,f,0,no.
26,a,45.00,0.000458,u,g,k,h,1.000,f,f,0,t,s,240.0,0,2400000.0,NaN,0,no.
27,a,30.42,0.000138,u,g,W,h,0.040,f,t,3,f,g,0.0,33,0.0,NaN,0,no.
28,a,NaN,0.000350,u,g,d,v,3.000,t,f,0,t,g,300.0,0,3000000.0,NaN,0,no.
29,b,17.25,0.000300,u,g,k,v,0.040,f,f,0,t,g,160.0,40,1600000.0,NaN,0,no.

In [6]:
###### see basics about the data
train.describe()

,variable2,variable3,variable8,variable11,variable14,variable15,variable17,variable19
count,3661.000000,3700.000000,3700.000000,3700.000000,3600.000000,3700.000000,3.600000e+03,3700.000000
mean,32.820713,0.000585,3.439496,4.160000,162.695000,2246.705946,1.626950e+06,0.925405
std,12.666181,0.000540,4.335229,6.750553,156.045682,8708.571126,1.560457e+06,0.262772
min,13.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000
25%,23.000000,0.000150,0.500000,0.000000,0.000000,0.000000,0.000000e+00,1.000000
50%,28.670000,0.000425,1.750000,2.000000,120.000000,113.000000,1.200000e+06,1.000000
75%,40.830000,0.000963,5.000000,6.000000,280.000000,1059.750000,2.800000e+06,1.000000
max,80.250000,0.002800,28.500000,67.000000,1160.000000,100000.000000,1.160000e+07,1.000000

In [7]:
print("total number of rows")
print(train.shape[0])
print("number of rows have  null values ")
print(train.shape[0]-(train.dropna(how="any")).shape[0])

# number of null rows is large so we can't simply delete these rows

total number of rows
3700
number of rows have  null values
2237

In [8]:
# number of rows that is all its values are null
print ("total number of rows")
print(test.shape[0])
print ("number of null rows ")
print(test.shape[0]-(test.dropna(how="any")).shape[0])

total number of rows
200
number of null rows
116

In [9]:

# see which columns have missing values

train.isnull().sum()

variable1       39
variable2       39
variable3        0
variable4       64
variable5       64
variable6       66
variable7       66
variable8        0
variable9        0
variable10       0
variable11       0
variable12       0
variable13       0
variable14     100
variable15       0
variable17     100
variable18    2145
variable19       0
classLabel       0
dtype: int64

In [10]:
test.isnull().sum()

variable1       3
variable2       3
variable3       0
variable4       2
variable5       2
variable6       3
variable7       3
variable8       0
variable9       0
variable10      0
variable11      0
variable12      0
variable13      0
variable14      3
variable15      0
variable17      3
variable18    111
variable19      0
classLabel      0
dtype: int64

 we see that all columns have few null of nulls except variable18 (null ratio more than 50%)

- so i will handle variable 18 later but now other variables will be imputed (numeric values with mean() , string values with mode())

In [11]:
modes=["variable1","variable4","variable5","variable6","variable7"]
for col in modes:
    train[col].fillna(train[col].mode()[0],inplace=True)
    test[col].fillna(test[col].mode()[0],inplace=True)
    
modes=["variable14","variable17","variable2"]
for col in modes:
    train[col].fillna(train[col].mean(),inplace=True)
    test[col].fillna(test[col].mean(),inplace=True)
    


train.isnull().sum()

variable1        0
variable2        0
variable3        0
variable4        0
variable5        0
variable6        0
variable7        0
variable8        0
variable9        0
variable10       0
variable11       0
variable12       0
variable13       0
variable14       0
variable15       0
variable17       0
variable18    2145
variable19       0
classLabel       0
dtype: int64

### Now see correlaion between columns

In [12]:


corr=train.apply(lambda x: x.factorize()[0]).corr()
corr

,variable1,variable2,variable3,variable4,variable5,variable6,variable7,variable8,variable9,variable10,variable11,variable12,variable13,variable14,variable15,variable17,variable18,variable19,classLabel
variable1,1.000000,0.058529,-0.001978,0.044526,0.044526,-0.059088,0.050991,0.116893,-0.056598,0.073279,-0.029171,-0.135270,0.005259,0.168331,-0.019284,0.168331,0.012780,-0.035487,-0.035487
variable2,0.058529,1.000000,0.274491,-0.039123,-0.039123,-0.042639,-0.016691,0.097712,0.019879,-0.091633,0.100313,0.010094,0.044087,0.144707,0.145900,0.144707,0.004902,0.057925,0.057925
variable3,-0.001978,0.274491,1.000000,-0.073800,-0.073800,0.072217,-0.013799,0.146094,0.059148,-0.109798,0.188087,0.039457,-0.015757,0.032371,0.174686,0.032371,-0.015036,0.069974,0.069974
variable4,0.044526,-0.039123,-0.073800,1.000000,1.000000,-0.008422,-0.034440,-0.171110,-0.214103,0.166765,-0.104309,-0.171140,0.144363,0.042860,-0.086077,0.042860,0.116571,-0.102442,-0.102442
variable5,0.044526,-0.039123,-0.073800,1.000000,1.000000,-0.008422,-0.034440,-0.171110,-0.214103,0.166765,-0.104309,-0.171140,0.144363,0.042860,-0.086077,0.042860,0.116571,-0.102442,-0.102442
variable6,-0.059088,-0.042639,0.072217,-0.008422,-0.008422,1.000000,0.035999,0.177944,0.140957,-0.051057,0.003959,-0.081705,-0.173708,0.142643,0.000855,0.142643,0.009578,0.080151,0.080151
variable7,0.050991,-0.016691,-0.013799,-0.034440,-0.034440,0.035999,1.000000,0.093523,0.050948,-0.008675,0.109298,0.030605,-0.078400,0.016457,-0.080752,0.016457,-0.022485,0.047570,0.047570
variable8,0.116893,0.097712,0.146094,-0.171110,-0.171110,0.177944,0.093523,1.000000,0.241325,-0.209740,0.225857,-0.021079,-0.133712,0.140333,0.143299,0.140333,0.004149,0.158145,0.158145
variable9,-0.056598,0.019879,0.059148,-0.214103,-0.214103,0.140957,0.050948,0.241325,1.000000,-0.399801,0.275668,-0.063239,-0.392016,-0.004386,0.142053,-0.004386,-0.108476,0.545244,0.545244
variable10,0.073279,-0.091633,-0.109798,0.166765,0.166765,-0.051057,-0.008675,-0.209740,-0.399801,1.000000,-0.551843,0.010270,0.300049,-0.012774,-0.334691,-0.012774,0.181617,-0.218894,-0.218894
variable11,-0.029171,0.100313,0.188087,-0.104309,-0.104309,0.003959,0.109298,0.225857,0.275668,-0.551843,1.000000,0.022397,-0.162470,0.026454,0.323951,0.026454,-0.038178,0.178090,0.178090
variable12,-0.135270,0.010094,0.039457,-0.171140,-0.171140,-0.081705,0.030605,-0.021079,-0.063239,0.010270,0.022397,1.000000,0.113403,-0.186069,0.090432,-0.186069,0.015376,-0.042168,-0.042168
variable13,0.005259,0.044087,-0.015757,0.144363,0.144363,-0.173708,-0.078400,-0.133712,-0.392016,0.300049,-0.162470,0.113403,1.000000,-0.019330,-0.200016,-0.019330,0.089426,-0.013762,-0.013762
variable14,0.168331,0.144707,0.032371,0.042860,0.042860,0.142643,0.016457,0.140333,-0.004386,-0.012774,0.026454,-0.186069,-0.019330,1.000000,0.074055,1.000000,-0.021983,0.030069,0.030069
variable15,-0.019284,0.145900,0.174686,-0.086077,-0.086077,0.000855,-0.080752,0.143299,0.142053,-0.334691,0.323951,0.090432,-0.200016,0.074055,1.000000,0.074055,-0.064756,0.079569,0.079569
variable17,0.168331,0.144707,0.032371,0.042860,0.042860,0.142643,0.016457,0.140333,-0.004386,-0.012774,0.026454,-0.186069,-0.019330,1.000000,0.074055,1.000000,-0.021983,0.030069,0.030069
variable18,0.012780,0.004902,-0.015036,0.116571,0.116571,0.009578,-0.022485,0.004149,-0.108476,0.181617,-0.038178,0.015376,0.089426,-0.021983,-0.064756,-0.021983,1.000000,-0.106082,-0.106082
variable19,-0.035487,0.057925,0.069974,-0.102442,-0.102442,0.080151,0.047570,0.158145,0.545244,-0.218894,0.178090,-0.042168,-0.013762,0.030069,0.079569,0.030069,-0.106082,1.000000,1.000000
classLabel,-0.035487,0.057925,0.069974,-0.102442,-0.102442,0.080151,0.047570,0.158145,0.545244,-0.218894,0.178090,-0.042168,-0.013762,0.030069,0.079569,0.030069,-0.106082,1.000000,1.000000

In [13]:
corr=test.apply(lambda x: x.factorize()[0]).corr()
corr

,variable1,variable2,variable3,variable4,variable5,variable6,variable7,variable8,variable9,variable10,variable11,variable12,variable13,variable14,variable15,variable17,variable18,variable19,classLabel
variable1,1.000000e+00,-0.023352,0.093426,-0.070427,-0.070427,0.062747,0.160550,0.093942,-0.018021,0.069544,0.081673,1.483598e-17,0.126668,-0.097159,0.024974,-0.097159,0.064157,-0.066815,-0.067873
variable2,-2.335204e-02,1.000000,0.360155,-0.100927,-0.100927,0.098805,0.058011,0.393483,-0.136146,0.100784,0.178788,1.564931e-02,0.048764,0.446654,0.404003,0.446654,0.066912,-0.023474,0.203301
variable3,9.342599e-02,0.360155,1.000000,-0.004177,-0.004177,0.170251,0.254666,0.405679,-0.150950,0.143580,0.180989,-2.049228e-02,0.047674,0.187193,0.200487,0.187193,0.093758,-0.043957,0.214476
variable4,-7.042667e-02,-0.100927,-0.004177,1.000000,1.000000,0.035031,-0.013618,-0.160119,0.098184,-0.128449,-0.106321,1.046299e-01,-0.003040,-0.117275,-0.136625,-0.117275,0.002184,-0.127881,-0.158147
variable5,-7.042667e-02,-0.100927,-0.004177,1.000000,1.000000,0.035031,-0.013618,-0.160119,0.098184,-0.128449,-0.106321,1.046299e-01,-0.003040,-0.117275,-0.136625,-0.117275,0.002184,-0.127881,-0.158147
variable6,6.274691e-02,0.098805,0.170251,0.035031,0.035031,1.000000,0.179394,0.013294,-0.113035,0.117786,0.173325,1.420025e-02,0.096357,0.059191,0.070445,0.059191,0.090170,-0.045441,0.178708
variable7,1.605498e-01,0.058011,0.254666,-0.013618,-0.013618,0.179394,1.000000,0.186284,-0.175899,0.216433,0.209348,9.731705e-02,0.047125,-0.002740,0.099188,-0.002740,0.048528,-0.183821,0.295379
variable8,9.394202e-02,0.393483,0.405679,-0.160119,-0.160119,0.013294,0.186284,1.000000,-0.347467,0.249841,0.282955,-6.275823e-02,0.051231,0.202800,0.271546,0.202800,0.086131,0.005274,0.294410
variable9,-1.802131e-02,-0.136146,-0.150950,0.098184,0.098184,-0.113035,-0.175899,-0.347467,1.000000,-0.522323,-0.452192,1.011443e-02,-0.039672,-0.165020,-0.180424,-0.165020,-0.142513,-0.030343,-0.720398
variable10,6.954358e-02,0.100784,0.143580,-0.128449,-0.128449,0.117786,0.216433,0.249841,-0.522323,1.000000,0.708750,8.006408e-02,0.218518,0.098330,0.358386,0.098330,0.245677,0.040032,0.569050
variable11,8.167319e-02,0.178788,0.180989,-0.106321,-0.106321,0.173325,0.209348,0.282955,-0.452192,0.708750,1.000000,7.967375e-02,0.174587,0.159201,0.377483,0.159201,0.156134,-0.056303,0.528066
variable12,1.483598e-17,0.015649,-0.020492,0.104630,0.104630,0.014200,0.097317,-0.062758,0.010114,0.080064,0.079674,1.000000e+00,0.130744,-0.099983,0.135207,-0.099983,-0.037573,-0.020000,0.090221
variable13,1.266678e-01,0.048764,0.047674,-0.003040,-0.003040,0.096357,0.047125,0.051231,-0.039672,0.218518,0.174587,1.307441e-01,1.000000,0.005994,0.212601,0.005994,0.110531,0.032686,0.079950
variable14,-9.715858e-02,0.446654,0.187193,-0.117275,-0.117275,0.059191,-0.002740,0.202800,-0.165020,0.098330,0.159201,-9.998340e-02,0.005994,1.000000,0.185042,1.000000,0.023429,0.184762,0.181715
variable15,2.497365e-02,0.404003,0.200487,-0.136625,-0.136625,0.070445,0.099188,0.271546,-0.180424,0.358386,0.377483,1.352067e-01,0.212601,0.185042,1.000000,0.185042,0.157034,-0.041824,0.298855
variable17,-9.715858e-02,0.446654,0.187193,-0.117275,-0.117275,0.059191,-0.002740,0.202800,-0.165020,0.098330,0.159201,-9.998340e-02,0.005994,1.000000,0.185042,1.000000,0.023429,0.184762,0.181715
variable18,6.415677e-02,0.066912,0.093758,0.002184,0.002184,0.090170,0.048528,0.086131,-0.142513,0.245677,0.156134,-3.757346e-02,0.110531,0.023429,0.157034,0.023429,1.000000,-0.087671,0.044571
variable19,-6.681531e-02,-0.023474,-0.043957,-0.127881,-0.127881,-0.045441,-0.183821,0.005274,-0.030343,0.040032,-0.056303,-2.000000e-02,0.032686,0.184762,-0.041824,0.184762,-0.087671,1.000000,0.010025
classLabel,-6.787267e-02,0.203301,0.214476,-0.158147,-0.158147,0.178708,0.295379,0.294410,-0.720398,0.569050,0.528066,9.022131e-02,0.079950,0.181715,0.298855,0.181715,0.044571,0.010025,1.000000

### From correlation analysic

-  we recognize (variable4 and varaible5) are totally correlated in both test and train data set
-  we recognize (varaible17 and varaible14) are totally correlated in both test and train data set
<br>
so we will remove variable 5  and varaible17

----------------------------------------
# Modification 1
-  we recognize (varaible18) has a weak correlaction with label and also has many Nan Values (more than 50%) and also i don't have other information to decide if this data is important or not
<br>
so we will remove variable18

# Modification 2 oversampling the data unblanced

# Modification 3 columns that is numbers
-----------------------------------------

-  we recognize classLabel and varaible19 are totally correlated in trian data set  but not in test so there is something wrong and can affect classificatio learning

# oversampling

# try to compy data of the minority again

neg=(train[train["classLabel"]=="no."])
for i in range(12):
    train=train.append(neg,ignore_index=True)
train

In [14]:
columns = ["variable5","variable17","variable18","variable19"]

train.drop(columns, axis=1, inplace=True)
test.drop(columns, axis=1, inplace=True)

print(train["variable1"].unique(),test["variable1"].unique())

['a' 'b'] ['b' 'a']

In [15]:

print(train.dtypes ==test.dtypes)

variable1     True
variable2     True
variable3     True
variable4     True
variable6     True
variable7     True
variable8     True
variable9     True
variable10    True
variable11    True
variable12    True
variable13    True
variable14    True
variable15    True
classLabel    True
dtype: bool

# ********** ******** ************** **************
# Encoding
# ********** ******** ************** **************

I will do oneHot encoding for catagorial data

In [16]:

categorical_feature_mask = train.dtypes==object
categorical_cols = train.columns[categorical_feature_mask].tolist()

In [17]:

le=None
for col in categorical_cols:
    le = LabelEncoder()
    train[col] = le.fit_transform(train[col])
    test[col] = le.transform(test[col])

In [18]:
sol=[]
for col in categorical_cols:
    sol.append(len(train[col].unique()))
    
print (sol)
categorical_cols.remove("classLabel")
for col in categorical_cols:
    oe=OneHotEncoder()
    x=oe.fit_transform(train[col].values.reshape(-1,1)).toarray()
    dfOneHot = pd.DataFrame(x, columns = [col+"_"+str(int(i)) for i in range(x.shape[1])])
    train = pd.concat([train, dfOneHot], axis=1)
    
    x=oe.transform(test[col].values.reshape(-1,1)).toarray()
    dfOneHot = pd.DataFrame(x, columns = [col+"_"+str(int(i)) for i in range(x.shape[1])])
    test = pd.concat([test, dfOneHot], axis=1)
    

train.head(20)

[2, 3, 14, 9, 2, 2, 2, 3, 2]

C:\Users\ramym\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\ramym\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\ramym\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\ramym\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\ramym\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\ramym\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\ramym\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\ramym\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)

,variable1,variable2,variable3,variable4,variable6,variable7,variable8,variable9,variable10,variable11,...,variable7_8,variable9_0,variable9_1,variable10_0,variable10_1,variable12_0,variable12_1,variable13_0,variable13_1,variable13_2
0,0,17.92,0.000054,1,2,7,1.750,0,1,1,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
1,1,16.92,0.000034,2,9,7,0.290,0,0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
2,1,31.25,0.000112,1,6,2,0.000,0,1,1,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
3,0,48.17,0.000133,1,7,6,0.335,0,0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
4,1,32.33,0.000350,1,9,7,0.500,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
5,0,34.83,0.000125,2,7,3,0.500,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
6,0,26.17,0.000200,1,8,4,0.000,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
7,1,21.17,0.000087,2,2,3,0.250,0,0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
8,1,28.92,0.000037,1,2,7,0.290,0,0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
9,1,18.17,0.001025,1,2,3,1.085,0,0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
10,0,24.75,0.001367,1,11,3,1.500,0,0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
11,0,31.75,0.000300,2,8,4,0.000,0,0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
12,0,18.17,0.001000,2,11,3,0.165,0,0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
13,0,18.25,0.001000,1,0,7,1.000,0,1,1,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
14,1,17.58,0.001000,1,0,3,0.165,0,1,1,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
15,1,51.83,0.000204,2,6,2,1.500,0,0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
16,1,26.67,0.001458,1,7,0,0.000,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
17,1,31.42,0.001550,1,2,7,0.500,1,0,0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
18,1,25.67,0.000325,1,2,3,2.290,0,1,1,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
19,1,33.75,0.000275,1,7,0,0.000,0,0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0

In [19]:
test.head(20)

,variable1,variable2,variable3,variable4,variable6,variable7,variable8,variable9,variable10,variable11,...,variable7_8,variable9_0,variable9_1,variable10_0,variable10_1,variable12_0,variable12_1,variable13_0,variable13_1,variable13_2
0,1,32.33,0.000750,1,5,0,1.585,1,0,0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
1,1,23.58,0.000179,1,2,7,0.540,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
2,1,36.42,0.000075,2,4,7,0.585,0,0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
3,1,18.42,0.001042,2,1,7,0.125,1,0,0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
4,1,24.50,0.001334,2,1,7,0.040,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
5,0,39.08,0.000400,1,2,7,3.000,0,0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
6,1,23.42,0.000100,1,2,7,0.500,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
7,1,29.58,0.000475,1,10,7,2.000,0,1,1,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
8,1,27.42,0.001250,1,1,0,0.250,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
9,1,58.58,0.000271,1,2,7,2.415,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
10,1,19.50,0.000959,1,1,7,0.790,0,0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
11,1,44.25,0.001100,2,4,7,1.500,1,0,0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
12,0,33.08,0.000162,1,4,7,0.540,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
13,1,40.58,0.000329,1,10,7,3.500,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
14,1,38.25,0.001012,2,9,7,0.125,0,0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
15,0,16.08,0.000034,1,6,2,0.000,0,1,1,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
16,1,26.75,0.000200,1,4,7,0.750,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
17,1,29.42,0.000125,1,0,7,1.750,0,0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
18,0,16.33,0.000021,1,1,7,0.125,0,0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
19,0,21.75,0.001175,1,2,7,0.250,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0

In [20]:
train.drop(categorical_cols, axis=1, inplace=True)
test.drop(categorical_cols, axis=1, inplace=True)

test.head()

,variable2,variable3,variable8,variable11,variable14,variable15,classLabel,variable1_0,variable1_1,variable4_0,...,variable7_8,variable9_0,variable9_1,variable10_0,variable10_1,variable12_0,variable12_1,variable13_0,variable13_1,variable13_2
0,32.33,0.000750,1.585,0,420.0,0,0,0.0,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
1,23.58,0.000179,0.540,0,136.0,1,0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
2,36.42,0.000075,0.585,0,240.0,3,0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
3,18.42,0.001042,0.125,0,120.0,375,0,0.0,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
4,24.50,0.001334,0.040,0,120.0,475,0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0

## Smote
oldColumns=train.columns
oldColumns=oldColumns.drop("classLabel")
oldColumns=oldColumns.append(pd.Index(["classLabel"]))
sm = SMOTE(sampling_strategy='minority', random_state=7)
oversampled_trainX, oversampled_trainY = sm.fit_sample(train.drop('classLabel', axis=1), train['classLabel'])
train = pd.concat([ pd.DataFrame(oversampled_trainX),pd.DataFrame(oversampled_trainY)], axis=1)
train.columns = oldColumns
train

In [21]:
train.to_csv("training_processed.csv",sep=';')
test.to_csv("validation_processed.csv",sep=';')